### ISSUE TITLE
Move to ITensor organization

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorWebsite#4]
I got confused for a bit and was looking in the old repository (https://github.com/ITensor/website) for the source code for the website.

I added a warning to that repository linking to this one and archived it (I assume that is ok with you, it just makes it read-only and it looks like it has not been edited for a while). It would also help to move this to the ITensor organization so it is easier to find.

**Comment by emstoudenmire** [comment]
Yes both good ideas! I had forgotten that this repo was still under my personal account.

A minor thing is that Dylan had set up a Github webhook in that other repo that automatically pulls any new changes onto our Amazon instance. Now that I set up this other repo that isn't working anymore. So one obvious thing could be to just move all of this code over to that old repo (and unarchive it of course). Or I could set up the webhook with this repo.

**Comment by emstoudenmire** [comment]
Ok I think it won't be hard to set up a new webhook after looking into it, so let's continue with this repo and move it into the ITensor organization.

**Comment by mtfishman** [comment]
Ok, sounds good. I'm fine either way.

**Comment by emstoudenmire** [comment]
Just moved it
