### ISSUE TITLE
Update Codes page

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorWebsite#7]
Looks like the codes page (https://itensor.org/codes) is a bit outdated. We should:

- [x] Add [ITensorMPS](https://github.com/ITensor/ITensorMPS.jl) to the "Official Julia Codes" section.
- [x] Move [ITensorGPU](https://github.com/ITensor/ITensorGPU.jl) to a new "Deprecated Julia Codes" section and update the URL.
- [x] Move [ITensorInfiniteMPS](https://github.com/ITensor/ITensorInfiniteMPS.jl) and [PastaQ](https://github.com/GTorlai/PastaQ.jl) to the "Experimental Julia Codes" section.
- [x] Update the URL of [ITensorGaussianMPS](https://github.com/ITensor/ITensorGaussianMPS.jl).
- [x] Add [ITensorTDVP](https://github.com/ITensor/ITensorTDVP.jl) to a new "Deprecated Julia Codes" section.

@emstoudenmire

**Comment by emstoudenmire** [comment]
Ok, updated. Please take a look and then we can close this issue.

**Comment by mtfishman** [comment]
Thanks!
