### ISSUE TITLE
Add NamedGraphs.jl and DataGraphs.jl to the Codes page

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensorWebsite#8]
Add [NamedGraphs](https://github.com/ITensor/NamedGraphs.jl) and [DataGraphs.jl](https://github.com/ITensor/DataGraphs.jl) to the "Supporting Libraries" section of the [Codes page](https://itensor.org/codes).

**Comment by emstoudenmire** [comment]
Any preference on how those should be ordered on the website? I'm updating it now.

**Comment by mtfishman** [comment]
Thanks! I think this would be good:
```
Observers   | SerializedElementArrays
NamedGraphs | DataGraphs
```
In terms of authors, it should be me and then Joey listed for NamedGraphs and just me for DataGraphs.

**Comment by mtfishman** [comment]
I realized also that the Julia packages should end in ".jl" on that page to make it clearer they are Julia packages.

**Comment by mtfishman** [comment]
It also could be good to add the following to the "Community Codes" sections:
- https://github.com/ITensor/ITensorCorrelators.jl
- https://github.com/ITensor/ITensorMPOConstruction.jl
- https://github.com/ITensor/ITensorAGP.jl
- https://github.com/JanReimers/ITensorMPOCompression.jl

The order listed above would be a reasonable order to add them in, based roughly on level of interest they might have in the community and also level of support. Probably they should go above the "DMRGPy" and "LindbladMPO" libraries in that section since they are Julia codes.

**Comment by emstoudenmire** [comment]
Ok, updated all those in PR #9
